services:
  postgres:
    image: postgres:17
    restart: always
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: catalogoapi
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    volumes:
      - pgadmindata:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80

volumes:
  pgdata:
    driver: local
  pgadmindata:
    driver: local
